server:
  port: 9080
  servlet:
    context-path: /spring-patch

swagger:
  enabled: true

spring:
  data:
    mongodb:
      uri: mongodb://admin:masterkey@localhost:27017/patch?authSource=admin
      auto-index-creation: true